version: "3.8"
services:
  juno:
    ports:
      - "6070:6070"
      - "6071:6071"
    environment:
      ETH_L1_RPC_URL: ws://execution.sepolia.dncore.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/sepolia/latest
      NETWORK: sepolia
      HTTP_PORT: 6070
      WS_PORT: 6071
