version: "3.8"
services:
  juno:
    image: juno.dnp.dappnode.eth:2.0.2
    ports:
      - "6070:6070"
      - "6071:6071"
    environment:
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/sepolia/latest
      NETWORK: sepolia
      HTTP_PORT: 6070
      WS_PORT: 6071
