version: "3.8"
services:
  juno:
    environment:
      ETH_L1_RPC_URL: ws://execution.sepolia.dncore.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/sepolia/latest
      NETWORK: sepolia
