version: "3.8"
services:
  juno:
    ports:
      - "6070:6070"
      - "6071:6071"
    environment:
      ETH_L1_RPC_URL: ws://execution.sepolia.dncore.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/sepolia/latest
      NETWORK: sepolia
      HTTP_PORT: 6070
      WS_PORT: 6071
  staking:
    image: nethermind/starknet-staking-v2:v0.3.0
    command:
      ["--metrics", "--metrics-host", "0.0.0.0", "--metrics-port", "9090"]
    environment:
      PROVIDER_HTTP_URL: http://juno-sepolia:6070/rpc/v0_9
      PROVIDER_WS_URL: ws://juno-sepolia:6071/ws/v0_9
      SIGNER_OPERATIONAL_ADDRESS: ""
      SIGNER_PRIVATE_KEY: ""
      SIGNER_EXTERNAL_URL: ""
