version: "3.8"
services:
  juno:
    build:
    image: juno.dnp.dappnode.eth:2.0.2
    ports:
      - "6060:6060"
      - "6061:6061"
    environment:
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/sepolia/latest
      NETWORK: sepolia
      HTTP_PORT: 6060
      WS_PORT: 6061
