version: "3.8"
services:
  juno:
    ports:
      - "6060:6060"
      - "6061:6061"
    environment:
      ETH_L1_RPC_URL: ws://execution.mainnet.dncore.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/mainnet/latest
      NETWORK: mainnet
      HTTP_PORT: 6060
      WS_PORT: 6061
