version: "3.8"
services:
  juno:
    environment:
      ETH_L1_RPC_URL: ws://execution.mainnet.dncore.dappnode:8546
      SNAPSHOT_URL: https://juno-snapshots.nethermind.io/files/mainnet/latest
      NETWORK: mainnet
